steps:
  mtaBuild:
    platform: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      deployTool: 'mtaDeployPlugin'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: '5e93c0a1trial'
      space: 'dev'
      credentialsId: 'CF-jenkins-credentials-id'